version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers

    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export PATH=${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin:$PATH' >> $BASH_ENV
            echo 'export BUNDLESIZE_GITHUB_TOKEN="f5fcce1e1e269e1e04cba6abe0619189b600ae43"' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run linter
          command: yarn run lint
      - run:
          name: Analyze bundle(s)
          command: yarn run analyze
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cache/yarn
